name: Backend CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar Poetry
        run: pip install poetry

      - name: Instalar dependências
        working-directory: backend
        run: poetry install --no-root

      - name: Executar testes
        working-directory: backend
        run: poetry run pytest